language: java
sudo: false
script: mvn verify

## Not trusty - openjdk11 install fails.
dist: xenial

jdk:
  - openjdk11

notifications:
  email:
    # [always|never|change]
    on_success: change
    on_failure: change
